### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KnightVVV** [Dr-WeiAL/RedAlert3-Remix#1]
**下面的选项需要在发送反馈后选中**
- [x] Bug出现时使用的是REMIX MOD自带地图
- [x] 未使用作弊器
- [x] 使用的REMIX为最新发布版本

**问题描述**
对遇到的问题是什么的简单清晰描述。

**复现方法**
复现bug的步骤：

1. 打开 '...'
2. 建造 '....'
3. 选择 '....'
4. ......
5. 出现bug

**预期行为**
对您期望发生的事情进行简单清晰的描述。

**截图**
如果可以的话，请添加截图信息以帮助我们更好的解决。

**更多信息**

 - 系统版本： [例如：win10 64位]
 - 系统内存： [例如：16GB]
 - mod版本： [例如：033]

**其他情况**
如果还有什么其他情况的话可以在这里写

**Comment by Dr-WeiAL** [comment]
好，没问题，我先关了
